In [5]:
import pandas as pd
import numpy as np
import seaborn as sns

In [6]:
df = pd.read_csv("/content/drive/MyDrive/Ai Medicaps(24 08 26)/ensemble ML/Clean_dataset.csv")

In [7]:
df

,Company,TypeName,Cpu,Ram,Gpu,OpSys,Weight,Price_inr,Touchscreen,IPS_Panel,PPI
0,Apple,Ultrabook,Intel Core i5,8,Intel Iris,Mac OS,1.37,147366,0,1,227.0
1,Apple,Ultrabook,Intel Core i5,8,Intel HD,Mac OS,1.34,98883,0,0,128.0
2,HP,Notebook,Intel Core i5,8,Intel HD,No OS,1.86,63250,0,0,141.0
3,Apple,Ultrabook,Intel Core i7,16,AMD Radeon,Mac OS,1.83,279120,0,1,221.0
4,Apple,Ultrabook,Intel Core i5,8,Intel Iris,Mac OS,1.37,198396,0,1,227.0
...,...,...,...,...,...,...,...,...,...,...,...
1247,Lenovo,2 in 1 Convertible,Intel Core i7,4,Intel HD,Linux/Android/Chrome OS,1.80,70180,1,1,157.0
1248,Lenovo,2 in 1 Convertible,Intel Core i7,16,Intel HD,Linux/Android/Chrome OS,1.30,164890,1,1,276.0
1249,Lenovo,Notebook,Other Intel Processor,2,Intel HD,Linux/Android/Chrome OS,1.50,25190,0,0,112.0
1250,HP,Notebook,Intel Core i7,6,AMD Radeon,Linux/Android/Chrome OS,2.19,84040,0,0,100.0


In [8]:
x = df.drop(columns = ['Price_inr'])

In [9]:
y = df['Price_inr']

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2 ,  random_state = 42 )

In [12]:
#ml flow n

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression

In [14]:
cat_fea = ['Company','TypeName','Cpu','OpSys','Gpu']

In [15]:
step1 = ColumnTransformer(transformers = [('col_tnf', OneHotEncoder(sparse_output = False, handle_unknown ='ignore'),cat_fea)], remainder = 'passthrough')
step2 = LinearRegression()

In [16]:
pipe = Pipeline ([('step1',step1),('step2',step2)])

In [17]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning: 
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(


Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('col_tnf',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Company', 'TypeName', 'Cpu',
                                                   'OpSys', 'Gpu'])])),
                ('step2', LinearRegression())])

In [18]:
y_pred = pipe.predict(x_test)

In [19]:
y_pred

array([136134.39724981,  71099.59113079,  96975.79100059, 145604.67409485,
       207852.58045149,  60407.91506919, 113676.9541437 , 138413.03855613,
        73756.63974732, 330645.58716816, 157763.68570364,  80930.44252212,
       137313.68950146,  57593.82661502,  55506.60096372, 130259.5822035 ,
       118398.26404614,  68384.49846143, 227504.77241959, 111320.00951432,
       176449.2288308 , 137139.38214574, 292129.75636429, 197106.54327127,
       116454.89921272, 153021.38252006,  42253.10411941, 167113.63031143,
        90050.35598375,  51872.36962681, 337578.72036074, 136809.21516423,
        51884.3453895 , 180764.12001363, 176493.61797144, 116351.9440554 ,
       131704.17070604, 153900.8699392 ,  35344.53897634, 121836.6326308 ,
       126262.74491415, 110602.14501852,  77831.39126217, 105778.76764824,
        48913.72943411, 228445.4499178 , 106203.14135615,  19668.42505371,
       105045.14083849, 134705.73918802, 101996.97870352,  85613.25482864,
        78766.55689285, 1

In [20]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [21]:
mse = mean_squared_error(y_test, y_pred)
mse

1070514825.1602955

In [22]:
r2 = r2_score(y_test, y_pred)*100
r2

77.04966524189784

In [23]:
men = mean_absolute_error(y_test, y_pred)
men

24869.393709810476

In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [25]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingRegressor

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [28]:
#KNN
stepkn1 = ColumnTransformer(transformers = [('col_tnf', OneHotEncoder(sparse_output = False, handle_unknown ='ignore'),cat_fea)], remainder = 'passthrough')
stepkn2 = KNeighborsClassifier()
pipe = Pipeline ([('step1',stepkn1),('step2',stepkn2)])
pipe.fit(x_train,y_train)
y_predkn = pipe.predict(x_test)
y_predkn


array([ 86350,  50490,  52690, 131890, 175780,  40590, 103950,  98890,
        60499, 146190, 208890,  53350, 193316,  29150,  43780, 104390,
       103180,  37840, 126390,  87890, 131670,  98890, 230890, 139480,
       108680, 126390,  51480, 131890, 111980,  55990, 164890,  72930,
        32890, 154770,  72490,  90090,  73590, 104390,  31790,  65889,
       104390,  73590,  85690, 105710,  32890, 131670, 105710,  27760,
        77990,  84700,  94600,  50490,  43890, 127930, 124190,  57090,
        62590,  53790,  61490,  37840,  61490,  72490,  76890,  84040,
        53350, 103180,  85690,  33990,  52690, 120890,  41690,  44990,
       124190,  75790, 107030,  98890,  93573,  29920,  88659,  33990,
        94490, 102507,  80190, 274890,  60499, 131890,  25190,  65889,
        79235, 110000, 131890,  50490,  80190, 147366, 131890,  47080,
       100540,  76890,  81950,  72490, 175780, 164450, 124190,  29150,
       140690,  98890,  22990,  72490, 159390,  38390, 131890,  86734,
      

In [29]:
mse = mean_squared_error(y_test, y_predkn)
mse

2474383071.486056

In [30]:
r2 = r2_score(y_test, y_predkn)*100
r2

46.95270119039899

In [31]:
men = mean_absolute_error(y_test, y_predkn)
men

32093.24701195219

In [32]:
#DT
stepdt1 = ColumnTransformer(transformers = [('col_tnf', OneHotEncoder(sparse_output = False, handle_unknown ='ignore'),cat_fea)], remainder = 'passthrough')
stepdt2 = DecisionTreeClassifier()
pipe = Pipeline ([('step1',stepdt1),('step2',stepdt2)])
pipe.fit(x_train,y_train)
y_preddt = pipe.predict(x_test)
y_preddt


array([119900,  50490,  52690, 183700, 175780,  79235, 103950, 150040,
        44990, 317335, 326480,  81620, 131890,  29150,  52678, 153890,
       150040,  37840, 241801, 118690, 141350,  98890, 164890,  98890,
       115419, 126390,  62920, 104390,  98010,  53018, 260700, 115390,
        81620, 154770, 150689,  99728, 182050, 197890,  31790,  70290,
       168850, 182050,  85690, 105710, 102520, 192170, 132770,  28490,
        77990, 103510, 108680,  50490,  44990, 127930, 176000,  87890,
        85360,  53790,  61490,  42790,  67760,  72490,  80946,  84040,
        67760, 150040,  85690,  40590,  52690, 184690,  41690,  39798,
       124190,  97790, 162250, 118690,  93573,  34980,  70289,  40590,
       180290, 213730,  80190, 274890,  44990, 144650,  25190, 125840,
        57090, 110000, 146850,  50490, 181500, 147366, 113051,  53350,
       107470,  58190, 329890,  92290, 223190, 164450, 326480,  67650,
       140690, 108899,  29920,  75790, 205700,  38280, 104390, 115390,
      

In [33]:
mse = mean_squared_error(y_test, y_preddt)
mse

2044736149.3984063

In [34]:
r2 = r2_score(y_test, y_preddt)*100
r2

56.16372793934972

In [35]:
men = mean_absolute_error(y_test, y_preddt)
men

27363.438247011953

In [36]:
#RF
step1rf = ColumnTransformer(transformers = [('col_tnf', OneHotEncoder(sparse_output = False, handle_unknown ='ignore'),cat_fea)], remainder = 'passthrough')
step2rf = RandomForestClassifier()
pipe = Pipeline ([('step1',step1rf),('step2',step2rf)])
pipe.fit(x_train,y_train)
y_predrf = pipe.predict(x_test)
y_predrf


array([119020,  50490,  52690, 188471, 175780,  79235, 105050,  91631,
        60499, 219230, 208890,  81620, 200750,  29150,  52678, 153890,
       150040,  37840, 153890, 141350, 141350,  98890, 252890, 184690,
       112089, 126390,  62920, 164890,  72491,  75790, 260700,  96690,
        81620, 233420, 142890, 194700, 156750,  87890,  31790,  70290,
       168850, 182050,  85690, 105710,  63250, 192170, 132770,  28490,
        77990,  96690, 105490,  50490,  43890, 128150, 176000,  86734,
        85360,  53790,  61490,  42790, 125702,  72490,  88000,  69190,
        61490, 103180, 108790,  40590,  52690, 184690,  41690,  59840,
        98890, 109890, 162250, 260700,  93573,  55000,  70289,  40590,
       135190,  76890,  80190, 274890,  60499,  73590,  25190, 125840,
        57529, 110000, 146850,  50490, 115390, 198396, 123190,  54879,
       107470,  43780,  92510,  92290, 223190, 205150, 176000,  22990,
       140690, 108899,  38280,  93170, 205700,  31460, 164890,  89974,
      

In [37]:
mse = mean_squared_error(y_test, y_predrf)
mse

1311103059.7768924

In [38]:
r2 = r2_score(y_test, y_predrf)*100
r2

71.89179129794296

In [39]:
men = mean_absolute_error(y_test, y_predrf)
men

22112.964143426296

In [43]:
from xgboost import XGBRegressor

In [44]:
#XG
step1xg = ColumnTransformer(transformers = [('col_tnf', OneHotEncoder(sparse_output = False, handle_unknown ='ignore'),cat_fea)], remainder = 'passthrough')
step2xg = XGBRegressor()
pipe = Pipeline ([('step1',step1xg),('step2',step2xg)])
pipe.fit(x_train,y_train)
y_predxg = pipe.predict(x_test)
y_predxg

array([108248.99 ,  49470.67 ,  61320.105, 171938.6  , 183366.11 ,
        80222.55 ,  91564.3  , 126671.98 ,  57604.38 , 380260.03 ,
       175929.92 ,  89677.16 , 176926.98 ,  49537.082,  42143.258,
       163947.22 , 142056.48 ,  38362.34 , 131424.23 ,  90914.91 ,
       157950.83 , 119597.414, 330177.9  , 196085.4  , 115066.29 ,
       154146.06 ,  56343.594, 167650.3  , 115262.25 ,  63582.484,
       331721.75 , 122285.91 ,  62555.51 , 192155.34 , 123993.13 ,
       151284.02 , 121070.586, 141411.75 ,  33667.098,  87816.125,
       165245.23 , 111953.18 ,  89041.664, 119773.89 ,  45558.34 ,
       227861.22 , 148631.97 ,  29295.334,  87423.58 ,  97302.39 ,
       103004.8  ,  52999.777,  52857.63 , 131855.81 , 197231.16 ,
        77188.92 ,  72984.85 ,  67588.17 ,  73396.41 ,  52794.902,
        81028.94 ,  76627.266,  83574.8  ,  84290.32 ,  76036.484,
       137591.75 ,  95481.71 ,  42868.02 ,  61320.105, 127624.664,
        43294.44 ,  50348.51 , 158587.77 , 102080.875, 149046.

In [45]:
print("R_2 Score for XGBRegressor",r2_score(y_test,y_predxg))
print("Mean Absolute Error XGBRegressor",mean_absolute_error(y_test,y_predxg))
print("Mean Squared Error XGBRegressor",mean_squared_error(y_test,y_predxg))

R_2 Score for XGBRegressor 0.7712305188179016
Mean Absolute Error XGBRegressor 19869.5078125
Mean Squared Error XGBRegressor 1067091712.0


In [47]:
#GradientBoostingRegressor
step1 = ColumnTransformer(transformers = [
    ('col_tnf',OneHotEncoder(sparse_output = False, handle_unknown = 'ignore'),cat_fea)
],remainder = 'passthrough')

step2 = GradientBoostingRegressor( n_estimators=500)

pipe = Pipeline([('step1',step1),('step2',step2)])

#Training the model stored in Pipe
pipe.fit(x_train, y_train)

y_pred = pipe.predict(x_test)  #Storing the Pred made by the machine
print("R_2 Score for GradientBoostingRegressor",r2_score(y_test,y_pred))
print("Mean Absolute Error GradientBoostingRegressor",mean_absolute_error(y_test,y_pred))
print("Mean Squared Error GradientBoostingRegressor",mean_squared_error(y_test,y_pred))


R_2 Score for GradientBoostingRegressor 0.7764430399872253
Mean Absolute Error GradientBoostingRegressor 19236.862103707612
Mean Squared Error GradientBoostingRegressor 1042777992.0593762
